site_name: MacedonIA Docs
theme:
  name: material
  palette:
    # Cambiar a modo oscuro automÃ¡ticamente segÃºn preferencias del sistema
    scheme: preference
    primary: teal
    accent: purple
  features:
    - navigation.expand # Abre los menÃºs automÃ¡ticamente

nav:
  - Inicio: index.md
  - Arquitectura:
    - ğŸ‰ Core (Watermelon): core/index.md
    - ğŸ‡ Network (Blackberry): network/index.md
    - ğŸ§  IA (Walnut): ai/index.md
    - ğŸŠ Web (Tangerine): web/index.md
  - Extensiones:
    - ğŸ« Skills (Blueberries): skills/index.md
    - ğŸ’ Plugins (Cherry): plugins/index.md
  - Extras: 
