site_name: MacedonIA Docs
theme:
  name: material
  palette:
    scheme: preference
    primary: teal
    accent: purple
    
  features:
    - navigation.tabs        
    - navigation.sections   
    - search.suggest        

  markdown_extensions:
    - admonition               
    - pymdownx.highlight       
    - pymdownx.superfences      
  nav:
  - Inicio: index.md
  - Arquitectura:
    - ğŸ‰ Core (Watermelon): core/index.md
    - ğŸ‡ Network (Blackberry): network/index.md
    - ğŸ§  IA (Walnut): ai/index.md
    - ğŸŠ Web (Tangerine): web/index.md
  - Extensiones:
    - ğŸ« Skills (Blueberries): skills/index.md
    - ğŸ’ Plugins (Cherry): plugins/index.md
  - Extras: 
